--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 21/08/2024 8:20:45 am
-- Server version: 8.0.30
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE quiz_app_db;

--
-- Drop table `activity_logs`
--
DROP TABLE IF EXISTS activity_logs;

--
-- Drop table `questions`
--
DROP TABLE IF EXISTS questions;

--
-- Drop table `quiz_history`
--
DROP TABLE IF EXISTS quiz_history;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop table `user_question_answers`
--
DROP TABLE IF EXISTS user_question_answers;

--
-- Set default database
--
USE quiz_app_db;

--
-- Create table `user_question_answers`
--
CREATE TABLE user_question_answers (
  id int NOT NULL AUTO_INCREMENT,
  user_id int DEFAULT NULL,
  question_id int DEFAULT NULL,
  answer varchar(255) DEFAULT NULL,
  created_by int DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by int DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  deleted_by int DEFAULT NULL,
  deleted_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 131,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `users`
--
CREATE TABLE users (
  id int NOT NULL AUTO_INCREMENT,
  lrn varchar(255) DEFAULT NULL,
  username varchar(255) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  first_name varchar(255) DEFAULT NULL,
  middle_name varchar(255) DEFAULT NULL,
  last_name varchar(255) DEFAULT NULL,
  dob date DEFAULT NULL,
  gender varchar(255) DEFAULT NULL,
  contact_no varchar(255) DEFAULT NULL,
  address varchar(2000) DEFAULT NULL,
  role_id int DEFAULT NULL,
  is_activated tinyint DEFAULT 0,
  created_by int DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by int DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  deleted_by int DEFAULT NULL,
  deleted_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `quiz_history`
--
CREATE TABLE quiz_history (
  id int NOT NULL AUTO_INCREMENT,
  user_id int DEFAULT NULL,
  category_id int DEFAULT NULL,
  score decimal(11, 2) DEFAULT NULL,
  no_of_questions decimal(11, 2) DEFAULT NULL,
  remarks varchar(255) DEFAULT NULL,
  no_of_attempts decimal(11, 2) DEFAULT 0.00,
  created_by int DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by int DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  deleted_by int DEFAULT NULL,
  deleted_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `questions`
--
CREATE TABLE questions (
  id int NOT NULL AUTO_INCREMENT,
  category_id int DEFAULT NULL,
  question varchar(2000) DEFAULT NULL,
  option_a varchar(2000) DEFAULT NULL,
  option_b varchar(2000) DEFAULT NULL,
  option_c varchar(2000) DEFAULT NULL,
  option_d varchar(2000) DEFAULT NULL,
  answer varchar(2000) DEFAULT NULL,
  created_by int DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by int DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  deleted_by int DEFAULT NULL,
  deleted_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 2048,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `activity_logs`
--
CREATE TABLE activity_logs (
  id int UNSIGNED NOT NULL AUTO_INCREMENT,
  action_taken varchar(4000) DEFAULT NULL,
  created_by int DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by int DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  deleted_by int DEFAULT NULL,
  deleted_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 528,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table user_question_answers
--
-- Table quiz_app_db.user_question_answers does not contain any data (it is empty)

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, '111-111', 'admin', '$2y$10$FvMxMZrntfgllNVl90tDbenxa6vPX.KKEfhtLo223tjIfEtQ/Yt42', 'ADMINISTRATOR', NULL, 'ADMINISTRATOR', '1998-07-30', 'MALE', '09614844561', 'MANILA', 1, 1, 1, '2024-08-10 20:24:31', NULL, NULL, NULL, NULL),
(2, '222-222', 'student1', '$2y$10$E4YsuQ/AL0.JF7/L5UscB.nqigcdpGpcExcGe.bfPNcK1n6NJVCWi', 'STUDENT', NULL, 'STUDENT', '2000-08-06', 'MALE', '09614844561', 'manila', 2, 1, 1, '2024-08-10 00:00:00', 2, '2024-08-10 20:21:19', NULL, NULL),
(4, NULL, 'STUDENT2', '$2y$10$RxQFN/rkz/QOgjMc9d6g7.zMd5lf34puWy3tXHhw2RPyKrT5LA4wK', 'STUDENT 2', NULL, 'STUDENT 2', '1998-07-29', 'MALE', '09614844561', 'MANILA', 2, 1, 1, '2024-08-10 20:36:22', NULL, NULL, NULL, NULL),
(5, NULL, 'student3', '$2y$10$b5TyE/DqsoSx08PD1YcpC.1fdtEcajynR1kNIXvGWXvRwYxb5cdLG', 'JUAN', NULL, 'DELA CRUZ', '2008-07-30', 'MALE', '09614844561', 'MANILA', 2, 1, 1, '2024-08-11 11:17:53', NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table quiz_history
--
-- Table quiz_app_db.quiz_history does not contain any data (it is empty)

-- 
-- Dumping data for table questions
--
INSERT INTO questions VALUES
(1, 1, 'What is the sum of 2/9  and  2/9?', '4/18', '4/9', '1/9', '2/18', '4/9', 1, '2024-08-20 22:44:02', NULL, NULL, NULL, NULL),
(2, 1, 'What is the sum of  2/12  and  8/12?', '8/12', '5/6', '12/6', '2/12', '5/6', 1, '2024-08-20 22:44:31', NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table activity_logs
--
INSERT INTO activity_logs VALUES
(1, 'LOGIN', 1, '2024-08-20 22:19:50', NULL, NULL, NULL, NULL);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;